package co.com.bvc.portal.mercados.servicio.imp;

import java.util.List;

import co.com.bvc.portal.mercados.servicio.IMercadoGeneral;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : MercadoResumenLogica.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Class MercadoResumenLogica.
 */
public class MercadoResumenLogica implements IMercadoGeneral {

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargaHistoricoIndice(int)
	 */
	public List<?> cargaHistoricoIndice(int idInidice) {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargaHistoricoIndiceIntradia(int)
	 */
	public List<?> cargaHistoricoIndiceIntradia(int idInidice) {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargaResumenMercados()
	 */
	public List<?> cargaResumenMercados() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargarFechaExdividendos()
	 */
	public List<?> cargarFechaExdividendos() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargarHorariosBursatil()
	 */
	public List<?> cargarHorariosBursatil() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.servicio.IMercadoGeneral#cargarTitulosTicker(int)
	 */
	public List<?> cargarTitulosTicker(int segmentoMercado) {
		// TODO Auto-generated method stub
		return null;
	}

	
}
