package co.com.bvc.portal.mercados.integracion.imp;

import java.util.List;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDivisasSetFXDAO.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IDivisasSetFXDAO.
 */
public interface IDivisasSetFXDAO {
	
	/**
	 * Cargar datos dia.
	 * 
	 * @return the list<?>
	 */
	public List<?> cargarDatosDia();

	/**
	 * Cargar resumen.
	 * 
	 * @return the list<?>
	 */
	public List<?> cargarResumen();
}
