package co.com.bvc.portal.mercados.servicio;

import java.util.HashMap;
import java.util.List;
import java.util.Set;

import co.com.bvc.portal.comun.excepcion.PersistenciaException;
import co.com.bvc.portal.mercados.modelo.BusquedaDerivados;
import co.com.bvc.portal.mercados.modelo.Derivado;
import co.com.bvc.portal.mercados.modelo.DerivadoCaracteristicasContrato;
import co.com.bvc.portal.mercados.modelo.DerivadoResumenContrato;
import co.com.bvc.portal.mercados.modelo.DerivadoResumenExtendido;
import co.com.bvc.portal.mercados.modelo.DerivadosAutocomplete;
import co.com.bvc.portal.mercados.modelo.MercadoDerivados;
import co.com.bvc.portal.mercados.persistencia.IDerivadosDao;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IDerivados.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IDerivados.
 */
public interface IDerivados {

	/**
	 * Metodo que devuelve el resumen de los derivados discriminados por los
	 * datos de la busqueda.
	 * 
	 * @param busqueda Opciones de la busqueda
	 * 
	 * @return {@link Set} resumen de los derivados para las opciones
	 * especificadas
	 * 
	 * @throws PersistenciaException 	 * @throws Exception the exception
	 */
	public Set<Derivado> getDerivados(BusquedaDerivados busqueda)
			throws Exception;


	/**
	 * Obtiene la lista de los tipos de contrato que existen.
	 * 
	 * @return the tipos contrato
	 */
	public HashMap<String, String> getTiposContrato();

	/**
	 * Metodo que obtiene el resumen de un contrato para un derivado dado su
	 * nemo.
	 * 
	 * @param nemo nemo con el que se va a buscar la información del derivado
	 * @param busquedaDerivados the busqueda derivados
	 * 
	 * @return {@link DerivadoResumenContrato} información de resumen del
	 * derivado
	 * 
	 * @throws PersistenciaException 	 * @throws Exception the exception
	 */
	public DerivadoResumenContrato getDerivadoResumenContrato(String nemo,
			BusquedaDerivados busquedaDerivados) throws Exception;

	/**
	 * Metodo que obtiene el resumen de un OPCF dado su vencimiento.
	 * 
	 * @param nemo the nemo
	 * @param busquedaDerivados the busqueda derivados
	 * 
	 * @return the derivado resumen contrato opcf
	 * 
	 * @throws Exception the exception
	 */
	public DerivadoResumenContrato getDerivadoResumenContratoOPCF(String nemo,
			BusquedaDerivados busquedaDerivados) throws Exception;

	/**
	 * Obtener total contratos ult dia.
	 * 
	 * @return el número de contratos.
	 * 
	 * @see IDerivadosDao.obtenerTotalContratosUltDia
	 */
	public Float obtenerTotalContratosUltDia();

	/**
	 * Derivados todas.
	 * 
	 * @return the list< derivados autocomplete>
	 */
	public List<DerivadosAutocomplete> derivadosTodas();

	/**
	 * Metodo que obtiene el resumen del mercado de derivados del día, si el parametro es nulo, se obtienen los valores del día actual.
	 * 
	 * @param busquedaDerivados the busqueda derivados
	 * 
	 * @return the mercado derivados
	 * 
	 * @throws Exception the exception
	 * 
	 * El conjunto de derivados.
	 */
	public Set<MercadoDerivados> getMercadoDerivados(
			BusquedaDerivados busquedaDerivados) throws Exception;
	
	/**
	 * Metodo que obtiene las características del contrato
	 * 
	 * @param busquedaDerivados the busqueda derivados
	 * 
	 * @return the mercado derivados
	 * 
	 * @throws Exception the exception
	 * 
	 * El conjunto de derivados.
	 */
	public DerivadoCaracteristicasContrato getCaracteristicasContrato(String nemo, 
			BusquedaDerivados busquedaDerivados);
	
	/**
	 * Metodo que obtiene el resumen del día del contrato
	 * 
	 * @param busquedaDerivados the busqueda derivados
	 * 
	 * @return Set<DerivadoResumenExtendido>
	 * 
	 * @throws Exception the exception
	 * 
	 * El conjunto de derivados.
	 */
	public Set<DerivadoResumenExtendido> getDerivadosDia(String nemoDerivado,
			BusquedaDerivados busquedaDerivados);
	
	public List<DerivadoResumenExtendido> getDerivadoResumenExtendidoGrafica(String nemo,BusquedaDerivados busquedaDerivados) throws Exception ;
	
}