package co.com.bvc.portal.mercados.servicio;

import java.util.List;

import co.com.bvc.portal.mercados.modelo.Especie;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IEspecieMercado.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IEspecieMercado.
 */
public interface IEspecieMercado extends IMercado {
	
	/**
	 * Gets the lista especie activa.
	 * 
	 * @return the lista especie activa
	 */
	public List<?> getListaEspecieActiva();

	/**
	 * Gets the lista especie inactiva.
	 * 
	 * @return the lista especie inactiva
	 */
	public List<?> getListaEspecieInactiva();

	/**
	 * Gets the detalle especie.
	 * 
	 * @param accion the accion
	 * 
	 * @return the detalle especie
	 */
	public Especie getDetalleEspecie(int accion);

}