package co.com.bvc.portal.mercados.servicio;

import java.util.Date;
import java.util.List;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IMercado.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IMercado.
 */
public interface IMercado {
	
	/**
	 * Gets the resumen especie dia.
	 * 
	 * @param dia the dia
	 * 
	 * @return the resumen especie dia
	 */
	public List<?> getResumenEspecieDia(Date dia);

	/**
	 * Gets the operaciones especie dia.
	 * 
	 * @param dia the dia
	 * @param especie the especie
	 * 
	 * @return the operaciones especie dia
	 */
	public List<?> getOperacionesEspecieDia(Date dia, int especie);

	/**
	 * Gets the estado mercado.
	 * 
	 * @return the estado mercado
	 */
	public boolean getEstadoMercado();

	/**
	 * Gets the cierres historico especie.
	 * 
	 * @param especie the especie
	 * 
	 * @return the cierres historico especie
	 */
	public List<?> getCierresHistoricoEspecie(int especie);
	
}
