package co.com.bvc.portal.mercados.servicio;

import java.util.List;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IMercadoGeneral.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IMercadoGeneral.
 */
public interface IMercadoGeneral {
	
	/**
	 * Carga resumen mercados.
	 * 
	 * @return the list<?>
	 */
	public List<?> cargaResumenMercados();

	/**
	 * Carga historico indice intradia.
	 * 
	 * @param idInidice the id inidice
	 * 
	 * @return the list<?>
	 */
	public List<?> cargaHistoricoIndiceIntradia(int idInidice);

	/**
	 * Carga historico indice.
	 * 
	 * @param idInidice the id inidice
	 * 
	 * @return the list<?>
	 */
	public List<?> cargaHistoricoIndice(int idInidice);

	/**
	 * Cargar fecha exdividendos.
	 * 
	 * @return the list<?>
	 */
	public List<?> cargarFechaExdividendos();

	/**
	 * Cargar horarios bursatil.
	 * 
	 * @return the list<?>
	 */
	public List<?> cargarHorariosBursatil();

	/**
	 * Cargar titulos ticker.
	 * 
	 * @param segmentoMercado the segmento mercado
	 * 
	 * @return the list<?>
	 */
	public List<?> cargarTitulosTicker(int segmentoMercado);
}
