package co.com.bvc.portal.mercados.servicio;

import java.util.List;

import co.com.bvc.portal.comun.excepcion.PersistenciaException;
import co.com.bvc.portal.mercados.modelo.EmisorTitulo;
import co.com.bvc.portal.mercados.modelo.RentaFijaAutocomplete;
import co.com.bvc.portal.mercados.modelo.RentaFijaOperacion;
import co.com.bvc.portal.mercados.modelo.RentaFijaResumen;
import co.com.bvc.portal.mercados.modelo.RentaFijaResumenTitulo;
import co.com.bvc.portal.mercados.modelo.RentaFijaSumaOperacion;

// TODO: Auto-generated Javadoc
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IRentaFija.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Interface IRentaFija.
 */
public interface IRentaFija extends IEspecieMercado {

	/**
	 * Gets the renta fija detalle operaciones.
	 * 
	 * @param dia
	 *            the dia
	 * @param tipoSesion
	 *            the tipo sesion
	 * @param tipoOperacion
	 *            the tipo operacion
	 * @param nemo
	 *            the nemo
	 * 
	 * @return the renta fija detalle operaciones
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */

	public List<RentaFijaOperacion> getRentaFijaDetalleOperaciones(String dia,
			String tipoSesion, String tipoOperacion, String nemo, String tipoMercado)
			throws PersistenciaException;

	/**
	 * Gets the resumen emisor.
	 * 
	 * @param nemo
	 *            the nemo
	 * 
	 * @return the resumen emisor
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */
	public EmisorTitulo getResumenEmisor(String nemo)
			throws PersistenciaException;

	/**
	 * Gets the resumen titulo.
	 * 
	 * @param nemo
	 *            the nemo
	 * 
	 * @return the resumen titulo
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */
	public RentaFijaResumenTitulo getResumenTitulo(String nemo)
			throws PersistenciaException;

	
	/**
	 * retorna el resumen del mercado de rentafija de acuerdo a los filtros dados como parametros.
	 * 
	 * @param dia
	 * 		La fecha consultada, o nulo en caso de querer consultar el día actual (En formato: yyyy-MM-dd).
	 * @param tipoDeuda
	 * 		Indica si se busca por deuda pública o deuda privada
	 * @param tipoOperacion
	 * 		Indica el tipo de operaciones que se estan buscando (Simultaneas, compraventas, repos, etc.)
	 * @param tipoSesion
	 * 		Indica la rueda de negociación (REG, TRD, BALO, etc.)
	 * @param tipoMercado
	 * 		Indica si se busca mercado transaccional, de registro o ambos.
	 * @return
	 * 		El resumen de rentafija acorde a los criterios de busqueda.
	 * 
	 * @throws PersistenciaException
	 */
	public RentaFijaResumen getResumen(String dia, String tipoDeuda,
			String tipoOperacion, String tipoSesion, String tipoMercado)
			throws PersistenciaException;

	/**
	 * Gets the resumen merge.
	 * 
	 * @param dia
	 *            the dia
	 * @param fechaFin
	 *            the fecha fin
	 * @param tipoDeuda
	 *            the tipo deuda
	 * @param tipoOperacion
	 *            the tipo operacion
	 * @param tipoSesion
	 *            the tipo sesion
	 * 
	 * @return the resumen merge
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */
	public RentaFijaResumen getResumenMerge(String dia, String fechaFin,
			String tipoDeuda, String tipoOperacion, String tipoSesion,
			String tipoMercado) throws PersistenciaException;

	// public RentaFijaResumen getResumenVariacionActive(String dia, String
	// fechaFin, String tipoDeuda, int tipoOperacion, String tipoSesion ) throws
	// PersistenciaException;

	/**
	 * Gets the suma operaciones grafica.
	 * 
	 * @param dia1
	 *            the dia1
	 * @param dia2
	 *            the dia2
	 * @param tipoSesion
	 *            the tipo sesion
	 * @param tipoOperacion
	 *            the tipo operacion
	 * @param nemo
	 *            the nemo
	 * 
	 * @return the suma operaciones grafica
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */
	public List<RentaFijaSumaOperacion> getSumaOperacionesGrafica(String dia1,
			String dia2, String nemo)
			throws PersistenciaException;

	/**
	 * Gets the renta fija autocomplete.
	 * 
	 * @return the renta fija autocomplete
	 * 
	 * @throws PersistenciaException
	 *             the persistencia exception
	 */
	public List<RentaFijaAutocomplete> getRentaFijaAutocomplete()
			throws PersistenciaException;

	public static final String MERCADO_TRANSACCIONAL = "T";

	public static final String MERCADO_REGISTRO = "R";

	public static final String MERCADO_TODOS = "%";

	/** The Constant DEUDA_PRIVADA. */
	public static final String DEUDA_PRIVADA = "PRIVADO";

	/** The Constant DEUDA_PUBLICO. */
	public static final String DEUDA_PUBLICO = "PUBLICO";

	/** The Constant DEUDA_ALL. */
	public static final String DEUDA_ALL = "TODOS";

	/** The Constant SESION_ALL. */
	public static final String SESION_ALL = "TODAS";

	/** The Constant SIMULTANEA. */
	public static final String SIMULTANEA = "SI";

	/** The Constant REPOS. */
	public static final String REPOS = "RR";

	/** The Constant TTV. */
	public static final String TTV = "TR";

	/** The Constant SWAP. */
	public static final String SWAP = "SW";

	/** The Constant CARRUSEL. */
	public static final String CARRUSEL = "CA";

	/** The Constant PLAZO. */
	public static final String PLAZO = "PL";

	/** The Constant NORMAL. */
	public static final String NORMAL = "CV";

	/** The Constant ALL_OPE. */
	public static final String ALL_OPE = "%";

	/** The Constant operaciones. */
	public static final String[] operaciones = { SIMULTANEA, REPOS, TTV, SWAP,
			CARRUSEL, PLAZO, NORMAL };

	/** The Constant operacionesName. */
	public static final String operacionesName[] = { "SIMULTANEA", "REPOS",
			"TTV", "SWAP", "CARRUSEL", "PLAZO", "NORMAL" };
}
