package co.com.bvc.portal.mercados.integracion;

import java.util.List;

import co.com.bvc.portal.mercados.integracion.imp.IDivisasSetFXDAO;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BusBVC.java
//  @ Date : 03/09/2008
//  @ Author : 
//
//

/**
 * The Class BusBVC.
 */
public class BusBVC implements IDivisasSetFXDAO {  

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.integracion.imp.IDivisasSetFXDAO#cargarDatosDia()
	 */
	public List<?> cargarDatosDia() {
		// TODO Auto-generated method stub
		return null;
	}

	/* (non-Javadoc)
	 * @see co.com.bvc.portal.mercados.integracion.imp.IDivisasSetFXDAO#cargarResumen()
	 */
	public List<?> cargarResumen() {
		// TODO Auto-generated method stub
		return null;
	}

}